import { RxDashboard } from "react-icons/rx";
import { RiStackLine } from "react-icons/ri";
import { IoSettingsOutline } from "react-icons/io5";
import { PiChalkboardTeacher } from "react-icons/pi";
import { CiMemoPad } from "react-icons/ci";
import { v4 as uid } from "uuid";

export const SidebarData = [
  {
    id: uid,
    heading: "Model Library",
    links: [
      {
        id: uid,
        name: "Model Library",
        icon: RxDashboard,
        href: "#",
      },
    ],
  },
  {
    id: uid,
    heading: "Extraction Builder",
    links: [
      {
        id: uid,
        name: "Label Data",
        icon: RxDashboard,
        href: "#",
      },
      {
        id: uid,
        name: "Model",
        icon: RiStackLine,
        href: "#",
      },
      {
        id: uid,
        name: "Test",
        icon: CiMemoPad,
        href: "#",
      },
    ],
  },
  {
    id: uid,
    heading: "Help",
    links: [
      {
        id: uid,
        name: "Settings",
        icon: IoSettingsOutline,
        href: "#",
      },
      {
        id: uid,
        name: "Support",
        icon: PiChalkboardTeacher,
        href: "#",
      },
    ],
  },
];

export const modelData = [
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Inactive",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
  {
    id: uid().replace(/-/g, "").slice(0, 7),
    name: "Blonde Drizzle",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, quo.",
    type: "Extraction",
    createdOn: new Date().toISOString(),
    lastTrained: new Date().toISOString(),
    status: "Active",
  },
];
